wget -O AndersonSherwood.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSCF7XHN/full/max/0/default.jpg
wget -O ArtsClubChicago.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSFVZZHH/full/max/0/default.jpg
wget -O BoardOfTrade.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS7CN7DT/full/max/0/default.jpg
wget -O BrundageSlim.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSLJEASY/full/max/0/default.jpg
wget -O ButcherFanny.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSL8B5RQ/full/max/0/default.jpg
wget -O CatherwoodMaryHartwell.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS26LU2Y/full/max/0/default.jpg
wget -O ConroyJack.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS5W9CGO/full/max/0/default.jpg
wget -O DarrowClarence.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZAEV5_Y/full/max/0/default.jpg
wget -O DebsEugene.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZA6NSVZ/full/max/0/default.jpg
wget -O FeenanMartin.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZUSEQDY/full/max/0/default.jpg
wget -O HechtBen.jpg https://collections.newberry.org/IIIF3/Image/2KXGDN86C24/full/max/0/default.jpg
wget -O MetcalfAntoinette.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8Z814RGLO/full/max/0/default.jpg
wget -O MetcalfIsaacStevens.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8Z819HT28/full/max/0/default.jpg
wget -O MetcalfMarion.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8Z814RSTQ/full/max/0/default.jpg
wget -O NewberryJulia.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS80YTZY/full/max/0/default.jpg
wget -O RasterAnnaSophie.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS75PAYB/full/max/0/default.jpg
wget -O RizalJose.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSSM15SN/full/max/0/default.jpg
wget -O RogersDaniel.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSM6EV_3/full/max/0/default.jpg
wget -O RuxtonGeorge.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8Z2JE17V/full/max/0/default.jpg
wget -O SaintMeminBenigne.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS75PFCR/full/max/0/default.jpg
wget -O SatterMark.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSMI2M32/full/max/0/default.jpg
wget -O ShawFrances.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS7H0ZMV/full/max/0/default.jpg
wget -O SmithWilliamEarl.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8Z81MEPUS/full/max/0/default.jpg
wget -O StobieCharles.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZSLTEEZZ/full/max/0/default.jpg
wget -O TaylorGraham.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS5RDGNP/full/max/0/default.jpg
wget -O WaldenMay.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZS75PJAX/full/max/0/default.jpg
wget -O WyattEdith.jpg https://collections.newberry.org/IIIF3/Image/2KXJ8ZA0OJDF/full/max/0/default.jpg
